### ISSUE TITLE
FATAL:setuid_sandbox_host.cc(157)

### ISSUE THREAD

**Issue by carlosnewmusic** [webtorrent/webtorrent-desktop#1703]
**What version of this package are you using?**
0.21 deb
**What operating system, Node.js, and npm version?**
kali linux, v12.10.0 , 6.10.3
**What happened?**
![imagen](https://user-images.githubusercontent.com/19379457/65151216-ead54000-da25-11e9-912b-ba6ba8cfd165.png)
**What did you expect to happen?**
which will start the program normally
**Are you willing to submit a pull request to fix this bug?**
no

**Comment by mathiasvr** [comment]
Related issue https://github.com/electron/electron/issues/17972.

Seems like this should be handled in `electron-installer-debian`, but does not work for Electron 6?

@carlosnewmusic For now, you have to run webtorrent-desktop with the `--no-sandbox` flag, or run the following commands to fix permissions: 
```
sudo chown root chrome-sandbox
chmod 4755 chrome-sandbox
```

**Comment by Francewhoa** [comment]
I can confirm a similar challenge with webtorrent-desktop_0.20.0-1_amd64.deb on Debian 8 Jessie

Steps to reproduce at #1705

**Comment by feross** [comment]
I'd like feedback from other collaborators on how to proceed here. It seems that downgrading to Electron 5 is one option to fix this? Is there another approach we should consider?

**Comment by hicom150** [comment]
Another approach that Microsoft's VSCode team took is to add `--no-sandbox` in the launch scripts (Desktop files) as we can see [here](https://github.com/microsoft/vscode/issues/81056).

It could be a relative easy fix until a better solution is given from electron team 😅

**Comment by feross** [comment]
That seems like a reasonable approach.

**Comment by hicom150** [comment]
If you want to reproduce this issue, you system should have `kernel.unprivileged_userns_clone` disabled. You can check this with the next command: `sudo sysctl kernel.unprivileged_userns_clone`

I'm my case, in Ubuntu 18.04.3 LTS is enabled by default so I've to disabled with `sudo sysctl kernel.unprivileged_userns_clone=0` to reproduce the issue.

BTW, I just send a PR #1707 that should fix the issue, but any help checking it in your system is welcome 😉

**Comment by amithm7** [comment]
I'm using  v0.24.0

This is not resolved for me:
![image](https://user-images.githubusercontent.com/7036770/94595926-0b76dd80-02a9-11eb-8b3f-50116db41263.png)

**Comment by Francewhoa** [comment]
I suggest to re-open this ticket. Because this error is back. This is to confirm this challenge is still present with WebTorrent v0.24.0

Using
* Debian 10 Buster
* WebTorrent 0.24.0 (0.108.6) (x64)
* GNOME 3.22.2

A temporary workaround is to start WebTorrent with this command: `webtorrent-desktop --no-sandbox`

**Comment by feross** [comment]
Re-opened since it appears this is still not fixed.
